services:
  postgres:
    container_name: mysql-estate
    image: mysql
    environment:
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
      MYSQL_DATABASE: real_state
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    restart: unless-stopped