spring:
  application:
    name: real-estate-api-monolithic
  datasource:
    url: jdbc:mysql://localhost:3306/real_state
    username: spring
    password: spring
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
server:
  port: 8080